version: "3.8"

services:
    effective-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "8080:8080"            
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
      image: postgres:15
      environment:
            POSTGRES_USER: user    
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: effective
      ports:
            - "5432:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data    
      healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d effective"]
            interval: 5s
            timeout: 5s
            retries: 10
volumes:
  postgres_data: